// Reading structure out of Postgres. Every object is rendered to one canonical
// text block with a deterministic line order, so a structure diff is a text
// diff and a renamed column is one line out, not a whole object rewritten.

import type { SQL } from "bun"
import type { DbObject } from "../model/snapshot"
import { textArray } from "./params"

/** STORE_SCHEMA is diffium-db's own schema; it never watches itself. */
export const STORE_SCHEMA = "diffium_db"

type ColumnRow = {
  schema: string
  table: string
  name: string
  type: string
  notnull: boolean
  dflt: string | null
  identity: string
  generated: string
}

type DefRow = { schema: string; table: string; name: string; def: string }
type EnumRow = { schema: string; name: string; label: string }
type ViewRow = {
  schema: string
  name: string
  kind: "view" | "matview"
  def: string
}
type FuncRow = { schema: string; name: string; args: string; def: string }

/** captureStructure renders every watched object in the given schemas. */
export async function captureStructure(sql: SQL, schemas: string[]): Promise<DbObject[]> {
  const [columns, constraints, indexes, triggers, enums, views, functions] = await Promise.all([
    sql.unsafe(COLUMNS_SQL, [textArray(schemas)]) as Promise<ColumnRow[]>,
    sql.unsafe(CONSTRAINTS_SQL, [textArray(schemas)]) as Promise<DefRow[]>,
    sql.unsafe(INDEXES_SQL, [textArray(schemas)]) as Promise<DefRow[]>,
    sql.unsafe(TRIGGERS_SQL, [textArray(schemas)]) as Promise<DefRow[]>,
    sql.unsafe(ENUMS_SQL, [textArray(schemas)]) as Promise<EnumRow[]>,
    sql.unsafe(VIEWS_SQL, [textArray(schemas)]) as Promise<ViewRow[]>,
    sql.unsafe(FUNCTIONS_SQL, [textArray(schemas)]) as Promise<FuncRow[]>,
  ])

  const tables = new Map<string, string[]>()
  const touch = (schema: string, table: string) => {
    const key = `${schema}.${table}`
    let lines = tables.get(key)
    if (!lines) {
      lines = [`table ${key}`]
      tables.set(key, lines)
    }
    return lines
  }

  for (const c of columns) {
    const bits = [c.type]
    if (c.identity === "a") bits.push("generated always as identity")
    else if (c.identity === "d") bits.push("generated by default as identity")
    if (c.notnull) bits.push("not null")
    if (c.dflt)
      bits.push(c.generated === "s" ? `generated always as (${c.dflt})` : `default ${c.dflt}`)
    touch(c.schema, c.table).push(`  column ${c.name} ${bits.join(" ")}`)
  }
  for (const r of constraints) touch(r.schema, r.table).push(`  constraint ${r.name} ${r.def}`)
  for (const r of indexes) touch(r.schema, r.table).push(`  index ${r.name} ${r.def}`)
  for (const r of triggers) touch(r.schema, r.table).push(`  trigger ${r.name} ${r.def}`)

  const out: DbObject[] = []
  for (const [key, lines] of tables) {
    const [schema, name] = splitKey(key)
    out.push({ key, kind: "table", schema, name, ddl: lines.join("\n") })
  }

  const enumLabels = new Map<string, string[]>()
  for (const e of enums) {
    const key = `${e.schema}.${e.name}`
    const labels = enumLabels.get(key) ?? []
    labels.push(e.label)
    enumLabels.set(key, labels)
  }
  for (const [key, labels] of enumLabels) {
    const [schema, name] = splitKey(key)
    const ddl = [`enum ${key}`, ...labels.map((l) => `  value ${l}`)].join("\n")
    out.push({ key, kind: "enum", schema, name, ddl })
  }

  for (const v of views) {
    const key = `${v.schema}.${v.name}`
    const head = v.kind === "matview" ? "materialized view" : "view"
    const ddl = [`${head} ${key}`, ...indent(v.def)].join("\n")
    out.push({ key, kind: v.kind, schema: v.schema, name: v.name, ddl })
  }

  for (const f of functions) {
    const key = `${f.schema}.${f.name}(${f.args})`
    const ddl = [`function ${key}`, ...indent(f.def)].join("\n")
    out.push({ key, kind: "function", schema: f.schema, name: f.name, ddl })
  }

  out.sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0))
  return out
}

/** watchedSchemas lists the non-system schemas of the connected database. */
export async function watchedSchemas(sql: SQL): Promise<string[]> {
  const rows = (await sql.unsafe(SCHEMAS_SQL, [STORE_SCHEMA])) as {
    name: string
  }[]
  return rows.map((r) => r.name)
}

function splitKey(key: string): [string, string] {
  const i = key.indexOf(".")
  return [key.slice(0, i), key.slice(i + 1)]
}

function indent(s: string): string[] {
  return s
    .trim()
    .split("\n")
    .map((l) => `  ${l.trimEnd()}`)
}

const SCHEMAS_SQL = `
select nspname as name
from pg_namespace
where nspname not in ('information_schema', $1)
  and nspname not like 'pg\\_%'
order by 1`

const COLUMNS_SQL = `
select n.nspname as schema, c.relname as table, a.attname as name,
       format_type(a.atttypid, a.atttypmod) as type,
       a.attnotnull as notnull,
       pg_get_expr(d.adbin, d.adrelid) as dflt,
       a.attidentity as identity,
       a.attgenerated as generated
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
left join pg_attrdef d on d.adrelid = c.oid and d.adnum = a.attnum
where c.relkind in ('r', 'p') and n.nspname = any($1::text[])
order by n.nspname, c.relname, a.attnum`

const CONSTRAINTS_SQL = `
select n.nspname as schema, c.relname as table, con.conname as name,
       pg_get_constraintdef(con.oid) as def
from pg_constraint con
join pg_class c on c.oid = con.conrelid
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = any($1::text[]) and c.relkind in ('r', 'p')
order by n.nspname, c.relname, con.conname`

// Indexes that back a constraint are already listed as that constraint.
const INDEXES_SQL = `
select n.nspname as schema, t.relname as table, i.relname as name,
       substring(pg_get_indexdef(i.oid) from ' USING (.*)$') as def
from pg_index x
join pg_class i on i.oid = x.indexrelid
join pg_class t on t.oid = x.indrelid
join pg_namespace n on n.oid = t.relnamespace
where n.nspname = any($1::text[])
  and not exists (select 1 from pg_constraint con where con.conindid = i.oid)
order by n.nspname, t.relname, i.relname`

const TRIGGERS_SQL = `
select n.nspname as schema, c.relname as table, t.tgname as name,
       substring(pg_get_triggerdef(t.oid) from ' (BEFORE|AFTER|INSTEAD OF) .*$') as def
from pg_trigger t
join pg_class c on c.oid = t.tgrelid
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = any($1::text[]) and not t.tgisinternal
order by n.nspname, c.relname, t.tgname`

const ENUMS_SQL = `
select n.nspname as schema, t.typname as name, e.enumlabel as label
from pg_type t
join pg_namespace n on n.oid = t.typnamespace
join pg_enum e on e.enumtypid = t.oid
where n.nspname = any($1::text[])
order by n.nspname, t.typname, e.enumsortorder`

const VIEWS_SQL = `
select n.nspname as schema, c.relname as name,
       case c.relkind when 'm' then 'matview' else 'view' end as kind,
       pg_get_viewdef(c.oid, true) as def
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
where c.relkind in ('v', 'm') and n.nspname = any($1::text[])
order by n.nspname, c.relname`

const FUNCTIONS_SQL = `
select n.nspname as schema, p.proname as name,
       pg_get_function_identity_arguments(p.oid) as args,
       pg_get_functiondef(p.oid) as def
from pg_proc p
join pg_namespace n on n.oid = p.pronamespace
join pg_language l on l.oid = p.prolang
where n.nspname = any($1::text[]) and p.prokind in ('f', 'p') and l.lanname <> 'internal'
order by n.nspname, p.proname, 3`
